# -*- coding: utf-8 -*-
"""VirtuDockDL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUcITO-_XntYuVhNyIvcjSfHvsZopilW
"""

!pip install -q condacolab
import condacolab; condacolab.install()
!conda install -c conda-forge pdbfixer -y -q

!sudo apt-get update -y
!sudo apt-get install python3.9 python3.9-distutils python3.9-dev -y

!wget https://bootstrap.pypa.io/get-pip.py
!python3.9 get-pip.py

!pip install dgl==1.1.3

!pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0

!pip install --ignore-installed blinker flask
!pip install pandas "numpy<2.0" scikit-learn matplotlib rdkit biopython
!pip install openmm
!pip install torch_geometric -q
!pip install pyyaml pydantic
!pip install flask
!pip install pyngrok
!pip install mdtraj

!git clone https://github.com/klocke3/VirtuDockDL_Colab.git > /dev/null 2>&1

import os
os.environ['MPLBACKEND'] = 'Agg'

!python /content/VirtuDockDL_Colab/app.py